---  
- name: allow local traffic input
  iptables:
    chain: INPUT
    in_interface: lo
    action: insert
    ctstate: NEW,ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes
  register: local_in

- name: allow local traffic
  iptables:
    chain: INPUT
    source: 10.0.0.0/8
    action: insert
    ctstate: NEW,ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes
  register: firewall_ten

- name: allow cloud boot traffic
  iptables:
    chain: INPUT
    source: 169.254.0.0/16
    action: insert
    ctstate: NEW,ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes
  register: firewall_cloud

- name: allow local traffic
  iptables:
    chain: INPUT
    action: insert
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes
  register: related

- name: log blocked traffic
  iptables:
    chain: INPUT
    in_interface: bond0
    action: append
    log_prefix: dropped
    jump: LOG
  become: yes
  register: firewall_log

- name: log outgoing traffic
  iptables:
    chain: OUTPUT
    action: insert
    log_prefix: output
    jump: LOG
  become: yes
  register: log_output

- name: block incoming external traffic
  iptables:
    chain: INPUT
    policy: DROP  
  become: yes
  register: firewall_reject

- name: install iptables-persistent
  package: name=iptables-persistent update_cache=yes force=yes state=present
  when: ansible_os_family == "Debian"

- name: save iptables
  shell: iptables-save > /etc/iptables/rules.v4
  become: true
  when: 
    - local_in
    - firewall_ten
    - firewall_cloud
    - firewall_reject
    - log_output
    - firewall_log
    - related
